# login: &login
#   username: root
#   password: \planb56b6!

development:
  adapter: mysql
  host: localhost
  database: prod_test
  username: root
  password: "%planb56b6!"
  # <<: *login

test:
  adapter: mysql
  host: localhost
  database: test
  username: root
  password: "%planb56b6!"
  # <<: *login

production:
  adapter: mysql
  host: localhost
  database: production
  username: root
  password: "%planb56b6!"
  # <<: *login
