development:
  adapter: mysql
  host: localhost
  database: prod_test
  username: root
  password: "%planb56b6!"
  reconnect: true

test:
  adapter: mysql
  host: localhost
  database: test
  username: root
  password: "%planb56b6!"
  reconnect: true

production:
  adapter: mysql
  host: localhost
  database: production
  username: root
  password: "%planb56b6!"
  reconnect: true
