development:
  adapter: mysql2
  host: localhost
  database: prod_test
  username: root
  password: "%planb56b6!"

test:
  adapter: mysql2
  host: localhost
  database: test
  username: root
  password: "%planb56b6!"

production:
  adapter: mysql2
  host: localhost
  database: production
  username: root
  password: "%planb56b6!"
