#!/bin/bash

cd ~/Dropbox/git/nom_it; rvm use ree@nom; rails runner Geocode.current_regions
cd ~/Dropbox/git/nom_it; rvm use ree@nom; rails runner Foursquare.fetch
cd ~/Dropbox/git/nom_it; rvm use ree@nom; rails runner NomRank.rank_v2
