#!/bin/bash

rvmsudo gem update --system
# rvmsudo gem install rails --no-ri --no-rdoc
# rvmsudo env ARCHFLAGS="-arch x86_64" gem install mysql -with-mysql-config=/usr/local/mysql/bin/mysql_config
# rvmsudo gem install bundler rake rack httparty unicorn mysql2 ruby-mysql --no-ri --no-rdoc
# rvmsudo gem install json mongo placefinder aws-s3 dalli memcache-client jquery-rails --no-ri --no-rdoc
