#!/bin/bash

sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y libssl-dev openssl ncurses-dev 
sudo apt-get install -y libreadline6 libreadline6-dev
sudo apt-get install -y zlib1g zlib1g-dev libyaml-dev libxml2-dev libxslt-dev libc6-dev
sudo apt-get install -y python-software-properties build-essential 
sudo apt-get install -y ruby-full curl autoconf automake libtool bison cmake make
sudo apt-get install -y imagemagick libmagickcore-dev
mkdir -p ~/log
